name: green_go
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  #view

  flutter_staggered_grid_view: ^0.7.0
  animations: ^2.0.8
  fl_chart: ^0.66.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  badges: ^3.1.2
  cached_network_image: ^3.3.0
  modal_bottom_sheet: ^3.0.0-pre
  map_launcher: ^3.1.0
  expandable: ^5.0.1
  gap: ^3.0.1
  easy_mask: ^2.0.1
  shimmer: ^3.0.0
  flutter_slidable: ^3.0.1
  pin_code_fields: ^8.0.1
  flutter_html: ^3.0.0-beta.1
  qr_flutter: ^4.1.0
  flutter_linkify: ^6.0.0
  webview_flutter: ^4.4.2
  flutter_staggered_animations: ^1.1.1
  flutter_holo_date_picker: ^1.1.3
  yandex_mapkit: ^4.0.2
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.0.9
  flutter_multi_formatter: ^2.12.1
  eva_icons_flutter: ^3.1.0
  
  #maps
  geolocator: ^10.1.0

  #nav
  go_router: ^12.1.1
  dio: ^5.3.4
  url_launcher: ^6.2.1
  pretty_dio_logger: ^1.3.1

  #log
  logger: ^2.0.2+1

  #state
  hooks_riverpod: ^2.4.8
  flutter_hooks: ^0.20.3
  
  #functional
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1
  uuid: ^4.2.1
  equatable: ^2.0.5
  keyboard_dismisser: ^3.0.0
  change_app_package_name: ^1.1.0

  #firebase
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6
  firebase_crashlytics: ^3.4.6
  firebase_analytics: ^10.7.2
  firebase_remote_config: ^4.3.6
  
  flutter_local_notifications: ^16.2.0
  flutter_app_badger: ^1.5.0

  #device specific
  package_info_plus: ^5.0.1
  android_id: ^0.3.6

  #persistance
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.8.3
  path_provider: ^2.1.1

  fluttertoast: ^8.2.4

  #permission
  permission_handler: ^11.1.0
  sliver_tools: ^0.2.12
  flutter_secure_storage: ^9.0.0

  #splash
  flutter_native_splash: ^2.3.6
  stack_trace:
  material_floating_search_bar_2: ^0.5.0
  flutter_typeahead: ^5.0.1
  syncfusion_flutter_datepicker: ^24.1.43
  audioplayers: ^5.2.1
  flutter_xlider: ^3.5.0
  device_info_plus: ^9.1.2
  mobile_scanner: ^4.0.1
  image_picker: ^1.0.7
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  lint: ^2.2.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^3.0.0

flutter:

  
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/config/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Semibold.ttf
          weight: 600

